CREATE TABLE TAG (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT PK_TAG PRIMARY KEY (id),
    CONSTRAINT UQ_TAG_NAME UNIQUE (name)
);

CREATE TABLE USERS (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (email)
);

CREATE TABLE TASK (
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    priority INT,
    status_type INT,
    severity_type INT,
    create_at TIMESTAMP NOT NULL,
    update_at TIMESTAMP,
    CONSTRAINT PK_TASK PRIMARY KEY (id),
    CONSTRAINT FK_TASK_USER FOREIGN KEY (user_id) REFERENCES USERS (id)
);

CREATE TABLE TASK_TAG (
    tag_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    CONSTRAINT PK_TASK_TAG PRIMARY KEY (tag_id, task_id),
    CONSTRAINT FK_TASK_TAG_TAG FOREIGN KEY (tag_id) REFERENCES TAG (id),
    CONSTRAINT FK_TASK_TAG_TASK FOREIGN KEY (task_id) REFERENCES TASK (id)
);